### ISSUE TITLE
Add dummy Database

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#1]
# Value Proposition

**As a** Developer 
**I want to** have a Database with all available products
so that I can work with them.

# Description

![Image](https://user-images.githubusercontent.com/107255827/184602155-2ef68957-729c-4633-9290-2d746a6e917b.png)

# Acceptance Criteria

- [x] The Database includes 7 example Products (3 coffee / 4 tea) 
- [x] The Products are categorised in `coffee` and `tea`
- [x] The Products have a `id,` `name` and `price` 

# Tasks

- [x] create new feature `branch` ("dummyDatabase")
- [x] create a `db.js` File.
- [x] Add the Products in a Array of Objects 
- [x] The Objects fulfill the Creteria's

# Complexity

XS

**Comment by ahohnsen** [comment]
Hey Niklas,

Good job 🚀 

I have a few minor suggestions:

> As a Admin
I want to have a Database with the Informations of the Products.
So that i can work with them.

I would write the user story from the developers point of view:

_As a developer
I want to have a database with the information of all available products
so that I can work with them._

> The Database includes all Products

Maybe it would be good to be a bit more specific here, e.g. how many products will there be.

Under task you do not need to write "for developers team" as the task list itself is meant to be for the developers anyway 🙂
