### ISSUE TITLE
Add "Add Button" to Product Card

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#10]
# Value Proposition

**As a** user
**I want to** have a Button on a Product Card
**So that** i can add the Product in the Shopping cart

# Description

![Image](https://user-images.githubusercontent.com/107255827/184831498-9fae74df-4bce-4e54-85bf-f6bdddd348c9.svg)

# Acceptance Criteria

- [ ] when the Button is clicked the Button color changes to green
- [ ] Text and Button are right-aligned in the Product Card

# Tasks

- [ ] create new feature `branch` ("AddToCardButton")
- [ ] create a Button with basic styling
- [ ] when the button is clicked the Product Card gets a state as "bookmarked"

# Complexity

S
