### ISSUE TITLE
Add product photos to product cards

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#11]
# Value Proposition

**As a** user
**I want to** see Photos of the Products on the Product Card Page
**So that** i can get an idea of the Products

# Description

![Image](https://user-images.githubusercontent.com/107255827/184881106-d1fd53c3-95c5-425b-93fe-b2453601be42.svg)

# Acceptance Criteria

- [x] can see all Products with Photos
- [x] the Photos are not clickable
- [x] the Photos scales with the Product Card

# Tasks

- [x] create new feature `branch` ("AddProductPhotos")
- [x] upload the images to the database (use links to unsplash)
- [x] use `Image Component` to show the photos on the product cards
- [x] add basic styling to the whole card

# Complexity

M

**Comment by JessicaLoers** [comment]
**Hi @LudiFlow @niklashmbgr** 
very nice User Story 👏

Just one minor comment regarding the first `AC` which is a little bit confusing - or perhaps I misunderstood 😁
I guess that users will `not only see the photos of the products they are interested` in, but `all the products with photos`. 
> can see Photos of the Products you are interested in

And I noticed one more thing in the `Tasks`: 

>  create a div within the product card in which the image will be shown

Probably you can use the `next js Image Component` 
For further information take a 👀 at the Docs : [next js Image Component](https://nextjs.org/docs/basic-features/image-optimization)

**Comment by JessicaLoers** [comment]
well done 👍
