### ISSUE TITLE
Update product quantity in shopping cart

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#16]
# Value Proposition

**As a** User
**I want to** update the quantity of a product in the shopping cart
**So that** I can easily order more than one product

# Description

![Image](https://user-images.githubusercontent.com/107849116/185798485-c4c6032e-89fb-43d3-aa0b-fc83f0af757d.png)

# Acceptance Criteria

- [x] on the product card there is a button group of two buttons ('plus' and 'minus'- button) 
- [x] between the button group there is a counter which can be controlled through the button group 
- [x] the shown price on each product card will be updated ( counter * single product price )

# Tasks

- [x] create new feature `branch` ("productQuantityCounter")
- [x] add button group to product card on shopping cart page 
- [x] create a counter with useState()
- [x] link counter to single product price 

# Complexity
L
