### ISSUE TITLE
Cart Banner

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#17]
# Value Proposition

**As a** User
**I want to** see a order summary
**So that** I know how much I have to pay and how many products I will receive 

# Description

![Image](https://user-images.githubusercontent.com/107849116/187162324-4c84ef9c-61e3-47d9-99c4-8d6aa2e53b8f.png)

# Acceptance Criteria

- [x] there is a 'CartBanner'-component just below the Header
- [x] the 'CartBanner'-component includes two tags
- [x] one tag shows the total price 
- [x] the other tag shows the total quantity 
- [x] each tag includes an Icon
- [x] the CartBanner 'flys' into the page 

# Tasks

- [x] create new feature `branch` ("cartBanner")
- [x] create 'cartBanner'-component
- [x] total price function 
- [x] total quantity function
- [x] implement function into CartBanner
- [x] use CSS-keyframes for CartBanner animation

# Complexity

M

**Comment by PhilipZi** [comment]
there should never be an "and" in "I want to see the total € amount and quantity of my order"

**Comment by Mersag** [comment]
Hallo Niklas,
ich finde, es sieht super aus und ich freue mich auf diese Funktion :-)
Falls ihr eure User Story doch ändern solltet ;
As a user
I would like to see an order overview
So that I have control over the costs.

Gruss, Meral
