### ISSUE TITLE
Add Counter Badge

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#18]
# Value Proposition

**As a** user
**I want to** have a counter badge below my shopping cart icon
**So that** I can see how many products are in the shopping cart 

# Description

![Image](https://user-images.githubusercontent.com/107849116/187698764-12364aab-c376-4e3a-869a-ee7b3039d5b6.png)

# Acceptance Criteria

- [x] the shopping cart badge can be seen right below the shopping cart symbol (default count: 0) 
- [x] the counter changes if a product is added to the cart 

# Tasks

- [x] create new feature `branch` ("CounterBadge")
- [x] create counter badge 
- [x] implement counter badge into Header-variant 

# Complexity

XS

**Comment by j-eick** [comment]
Nice 👍 

**Suggestion:** 
What if you make the icon a bit larger and then you place the counter badge "into" the icon?
