### ISSUE TITLE
Create Detailpage for each Product

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#19]
# Value Proposition

**As a** user
**I want to** click on the "info-Button" to see more informations of the product
**So that** i can see the quantity and preparation

# Description

![Image](https://user-images.githubusercontent.com/107255827/186128023-f5df0988-5943-4a6d-b5a7-b52cd4b5a5ca.svg)

# Acceptance Criteria

- [x] the user can click on the `info-button` to go to the detail page
- [x] when he clicks on "Add to Cart" the product is put into the shopping cart
- [x] if he clicks on "Back to Products" he gets back to the product page

# Tasks

(for developers team)

- [x] create new feature `branch` ("AddDetailPage")
- [x] extend the database with a `description` for each product
- [x] add "info" Icon to Productcard mit `Link` to the Detailpage
- [x] create a detail page on which the clicked product is displayed
- [x] create two buttons with the "Back" and "Add" Fuctions

# Complexity

L

**Comment by j-eick** [comment]
Will the detail page have its own url?

**Comment by TheRealFlow** [comment]
yes, that is the plan for now
