### ISSUE TITLE
Display Product Card with basic information

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#2]
# Value Proposition

**As a** shop administrator 
**I want to** see the details of a product
**So that** I can verify the data of the product 

# Description

![Image](https://user-images.githubusercontent.com/107849116/184626609-96a213ca-959a-469e-b8d8-de452deb915f.png)

# Acceptance Criteria

- [ ] the product card's are displayed
- [ ] the list of the products is scrollbar 

# Tasks

- [x] create new feature branch ("displayProduct")
- [x] use "dummy Database" which holds the data structure for a single product
- [x] create a product page 
- [x] create a  product component that receives data via props and renders it
- [x] add basic styling 
- [ ] add to storybook 

# Complexity

S

**Comment by ahohnsen** [comment]
Hey Niklas,

I have a few suggestions:

Scribble:
- I would suggest to draw your scribbles in portrait mode and not landscape. As well your scribble should be as realistic as possible, therefore it would be better to show a list of real products you have in your database instead of using placeholder text like _product name, product price_

Acceptance Criteria:
- You do not need to write what is already shown on the scribble. We should describe all the details which are not visible (e.g errors which might occur, possible user interactions ...). In this case you could for example mention if the products follow a certain order (alphabetically maybe?) and if the page is scrollable.

**Comment by RobertBReich** [comment]
Hey you two,

the list of the products is "scrollbar" should be scrollable 😂 
Other than that, looks cool. 👍

cheers
R.
