### ISSUE TITLE
Comment Field Shopping Cart

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#24]
# Value Proposition

**As a** user
**I want to** have a comment field in the shopping cart
**So that** i can specify my order

# Description

![Image](https://user-images.githubusercontent.com/107255827/187212432-961538af-10c0-43ea-b7b5-16809e252215.png)

# Acceptance Criteria

- [x] the comment field is a text input field that allows a maximum of 100 characters and is not required

# Tasks

- [x] create new feature `branch`
- [x] create a `textarea` with character limit for the order comments 

# Complexity

S
