### ISSUE TITLE
Add select options for order

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#25]
# Value Proposition

**As a** user
**I want to** select between "To-Go" or "In-House"
**So that** i can choose where to have my drink 

# Description

![Image](https://user-images.githubusercontent.com/107255827/187217499-f1bd41ef-755f-46a6-ae32-caf1cb565401.png)

# Acceptance Criteria

- [ ] the "in-house" checkbox is preselected
- [ ] a table number must be selected via drop-down menu when "in-house" is checked
- [ ] if "to-go" is selected the drop-down menu is disable and a order number appears after checkout button is clicked

# Tasks

- [ ] create new feature `branch`
- [ ] create two checkboxes ("to-do" and "in-house") one is preselected
- [ ] create a select input with numbered options (1-12)
- [ ] disable the drop-down menu if "to-go" is selected
- [ ] disable the checkout button if none checkbox is selected 

# Complexity

L

**Comment by j-eick** [comment]
Looks good! 👍🏼

Suggestions:
If user chooses TO-GO, you could give the user a hint that he'll receive his order number, as soon as he click "checkout".

> Checkout to receive your order number. 

Just a thought.
