### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#28]
# Value Proposition

**As a** Developer
**I want to** have a Layout 
**So that** my design is better structured 

# Description

![Image](https://user-images.githubusercontent.com/107849116/187449573-1e189b32-9056-42d0-be4f-68f61d285540.png)

# Acceptance Criteria

- [x] there is a dynamic Layout Component 
- [x] the Layout Component includes: Header + Main 

# Tasks

- [x] create new feature `branch` ("Layout")
- [x] create Layout (with {children}) Component
- [x] change content of Header 
- [x] implement Layout Component into HomePage and ShoppingCartPage 

# Complexity

S

**Comment by Mersag** [comment]
Looks good.
