### ISSUE TITLE
Shopping Cart Page

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#3]
# Value Proposition

**As a** User
**I want to** have a shopping cart 
**So that** I have an overview of the product's which i like to order

# Description

![Image](https://user-images.githubusercontent.com/107849116/184631732-1b3ade71-e8f1-4861-89fc-0cde198cd09a.png)

# Acceptance Criteria

- [ ] there is a shopping cart page 
- [ ] all added product's are shown on this page 
- [ ] there is a button with an arrow 
- [ ] clicking on the button returns the user to the product page 

# Tasks

- [ ] create new feature branch ("shoppingCartPage")
- [ ] create a shopping cart page 
- [ ] add a button with an arrow
- [ ] route the button to the product page 
- [ ] add basic styling

# Complexity

M

**Comment by RobertBReich** [comment]
Looks great!
