### ISSUE TITLE
Testing Buttons

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#31]
# Value Proposition

**As a** developer
**I want to** have my button's tested 
**So that** I can be sure that there are working correctly

# Acceptance Criteria

- [x] all test's are successful

# Tasks

- [x] create new feature `branch` ("testButton")
- [x] test if the button renders correctly
- [x] test if the onClick-event is working

# Complexity

M

**Comment by ckskr** [comment]
You can describe what the buttons need to do to be correctly tested
