### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#34]
# Value Proposition

**As a** User
**I want to** have a styled application
**So that** I have a better user experience 

# Acceptance Criteria

- [ ] there are variables instead of individual color codes 
- [ ] the format is responsive 

# Tasks

(for developers team)

- [ ] create new feature `branch` ("Styling")
- [ ] add variables to GlobalStyles

# Complexity

M
