### ISSUE TITLE
Add Grid & Currency

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#35]
# Value Proposition

**As a** developer
**I want to** implement grid 
**So that** the individual product cards look better

# Acceptance Criteria

- [ ] the informations on the cards are rearranged
- [ ] the currency is displayed correctly
- [ ] the cards will be slightly larger than before

# Tasks

- [ ] create new feature `branch`
- [ ] add `display: grid` to each card component
- [ ] arrange the content user friendly
- [ ] convert the numbers into currency

# Complexity

M
