### ISSUE TITLE
Finish Design

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#38]
# Value Proposition

**As a** user
**I want to** see a good looking App
**So that** the user experience is better than before

# Acceptance Criteria

- [ ] the complete app gets a design polish
- [ ] small animations are added
- [ ] errors are fixed

# Tasks

- [ ] create new feature `branch`
- [ ] fix background image and header on the pages
- [ ] implement animation for the product cards
- [ ] fix style and color from components

# Complexity

L
