### ISSUE TITLE
Add product's to Shopping Cart

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#4]
# Value Proposition

**As a** User
**I want to** select the product which i want to order
**So that** the product is added to the shopping cart

# Description

![Image](https://user-images.githubusercontent.com/107849116/184851497-087b8d8a-e03f-4ae3-8b69-2c57aaadb447.png)

# Acceptance Criteria

Product Page:

- [x] there is a button to add the product to the shopping cart 
- [ ] by clicking the 'add to cart' button the item is added to the shopping cart and the color of the button changes to green (the user stays on the product page)
- [x] there is a ShoppingCart-Symbol 
- [x] by clicking the ShoppingCart-Symbol the user is redirected to the ShoppingCart-Page 

Shopping Cart Page:

- [x]  all added product's are shown on this page
- [x] by clicking the ('remove from cart') button the product should be deleted 
- [x] there is a button with an arrow on this page 
- [x] by clicking the button the user returns to the Product-Page

# Tasks

- [x] create new feature branch ("addProductShoppingCart")
- [x] add a "add to cart" button to the product component 
- [ ] add toggle function to the button 
- [x] add styling to the button 
- [x] add ShoppingCart-Symbol to the Product Page 
- [x] create a ShoppingCart-Page 
- [x] redirect the ShoppingCart-Symbol to the ShoppingCart-Page 
- [x] add a button with an arrow
- [x] route the button (arrow) to the Product Page

# Complexity

XL
