### ISSUE TITLE
Add Delete Button to Productcard

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#5]
# Value Proposition

**As a** User
**I want to** click on a Button on a Product
**So that** i can delete a Product in the Shopping Cart

# Description

![Image](https://user-images.githubusercontent.com/107255827/184371143-5f19c7dc-0a0c-4fbe-a92f-607669177a1a.png)

# Acceptance Criteria

- [ ] Every bookmarked Products are shown on the Page
- [ ] with click on the Button the Product can be deleted
- [ ] All other Products remain in the List

# Tasks

(for developers team)

- [ ] create new feature branch ("deleteButton")
- [ ] Create a Button that `filter` out the clicked Card
- [ ] Let re-rendering the Page

# Complexity

M
