### ISSUE TITLE
Add Checkout Button to Shopping Cart

### ISSUE THREAD

**Issue by TheRealFlow** [LudiFlow/capstone-project#6]
# Value Proposition

**As a** User.
**I want to** click on a Button in the Shopping Cart.
**So that** i can finish my Order.

# Description

![Image](https://user-images.githubusercontent.com/107849116/185352446-6c66ab36-d557-4da3-9d95-c972ec670953.png)

# Acceptance Criteria

- [x] The Button is shown on the bottom of the Page
- [x] When the Button is clicked, a success message appears
- [x] After that, the user gets redirected to the Product Page

# Tasks

- [x]  create new feature branch ("checkoutButton")
- [x] Create a Button with a `alert-function`
- [x] After the click, route to the Startpage after 2sec.

# Complexity

M
