### ISSUE TITLE
Add Header to Product Page

### ISSUE THREAD

**Issue by niklashmbgr** [LudiFlow/capstone-project#9]
# Value Proposition

**As a** Developer
**I want to** have a header in my application with an ShoppingCart-Icon
**So that** I can navigate to the ShoppingCart-Page

# Description

![Image](https://user-images.githubusercontent.com/107849116/184649085-68da5d0b-6751-446b-acb9-7707e5e5c51a.png)

# Acceptance Criteria

- [ ] the Header component includes a headline ("COFTEA") and a ShoppingCart-Icon 
- [ ] the ShoppingCart-Icon is clickable 
- [ ] after clicking the Icon the User is redirected to the ShoppingCart-Page 

# Tasks

- [ ] create new feature `branch` ("productPageHeader")
- [ ] create Header component
- [ ] add headline to Header component
- [ ] add ShoppingCart-Symbol  to Header component
- [ ] create an empty shopping cart page 
- [ ] navigate ShoppingCart-Icon to the ShoppingCart-Page 
- [ ] add basic styling
- [ ] add to storybook 

# Complexity

S
